### ISSUE TITLE
Have a better handling of error in the keychain's access

### ISSUE THREAD

**Issue by samuelmanzanera** [archethic-foundation/archethic-cli#30]
### Describe the problem you discovered

If we try to access a transaction already existing with no keychain attached we get a good response

![image](https://github.com/archethic-foundation/archethic-cli/assets/14906964/b2af0319-82bc-4f8c-86c7-78ca667acd26)

However if we try to access a transaction which does not exist we get this error

![image](https://github.com/archethic-foundation/archethic-cli/assets/14906964/b7a95fa7-0c16-47a0-8a32-bd5eb9cc091a)

### Describe the solution you'd like

We should have a better catching system in the graphql query.

Probably this is more related to https://github.com/archethic-foundation/libgo

**Comment by cluster** [comment]
Fixed when merging [this PR](https://github.com/archethic-foundation/archethic-cli/pull/45) which updates the libgo dependency to 1.0.4
